# Generated by Django 5.1.3 on 2024-11-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('nr', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pakape', models.CharField(max_length=100)),
                ('uzvards_un_vards', models.CharField(max_length=200)),
                ('dienesta_vieniba', models.CharField(max_length=200)),
                ('ordenis', models.CharField(default='Default Value', max_length=200)),
                ('ordeņa_pakape', models.CharField(blank=True, null=True)),
                ('piezimes', models.CharField(blank=True, max_length=255, null=True)),
                ('arhīva_lieta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='React',
            fields=[
                ('nr', models.CharField(default='Default Value', max_length=50, primary_key=True, serialize=False)),
                ('pakape', models.CharField(default='Default Value', max_length=100)),
                ('uzvards_un_vards', models.CharField(default='Default Value', max_length=200)),
                ('dienesta_vieniba', models.CharField(default='Default Value', max_length=200)),
                ('ordenis', models.CharField(default='Default Value', max_length=200)),
                ('ordeņa_pakape', models.CharField(blank=True, default='Default Value', null=True)),
                ('piezimes', models.CharField(blank=True, default='Default Value', max_length=255, null=True)),
                ('arhīva_lieta', models.CharField(default='Default Value', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
