# Generated by Django 5.1.3 on 2024-11-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zedelgema',
            fields=[
                ('nr', models.IntegerField(primary_key=True, serialize=False)),
                ('dienesta_pakape', models.CharField(max_length=50)),
                ('uzvards', models.CharField(max_length=50)),
                ('vards', models.CharField(max_length=50)),
                ('dzimsanas_datums', models.DateField()),
                ('dienesta_vieniba', models.TextField()),
                ('nometnes_nodalijums', models.IntegerField()),
                ('aizbraucis_uz_psrs', models.DateField(blank=True, null=True)),
                ('miris', models.DateField(blank=True, null=True)),
                ('piezimes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
