# Generated by Django 5.1.3 on 2024-11-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_zedelgema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zedelgema',
            name='nr',
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
