# Generated by Django 5.1.3 on 2024-11-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('nr', models.IntegerField(primary_key=True, serialize=False)),
                ('pakape', models.CharField(max_length=100)),
                ('uzvards_un_vards', models.CharField(max_length=200)),
                ('dienesta_vieniba', models.CharField(max_length=200)),
                ('ordenis', models.CharField(max_length=200)),
                ('ordeņa_pakape', models.IntegerField(blank=True, null=True)),
                ('piezimes', models.CharField(blank=True, max_length=255, null=True)),
                ('arhīva_lieta', models.CharField(max_length=50)),
            ],
        ),
    ]
