# Generated by Django 5.1.3 on 2024-11-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_brigade_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brigade',
            name='nr',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='ordeņa_pakape',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
