# Generated by Django 5.1.3 on 2024-11-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_zedelgema_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zedelgema',
            name='dzimsanas_datums',
            field=models.CharField(max_length=50),
        ),
    ]
