# Generated by Django 5.1.3 on 2024-11-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_brigade_nr_alter_brigade_ordeņa_pakape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brigade',
            name='arhīva_lieta',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
