# Generated by Django 5.1.3 on 2024-11-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_zedelgema_dzimsanas_datums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zedelgema',
            name='aizbraucis_uz_psrs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
