# Generated by Django 5.1.3 on 2024-11-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_brigade_arhīva_lieta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brigade',
            name='ordeņa_pakape',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='piezimes',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
