# Generated by Django 5.1.3 on 2024-11-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_zedelgema_aizbraucis_uz_psrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zedelgema',
            name='miris',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
