# Generated by Django 5.1.3 on 2024-11-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_brigade_ordeņa_pakape_alter_brigade_piezimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brigade',
            name='arhīva_lieta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='nr',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='ordeņa_pakape',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='piezimes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
