# Generated by Django 5.1.3 on 2024-11-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_brigade_arhīva_lieta_alter_brigade_nr_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brigade',
            new_name='Brigade2',
        ),
    ]
