# Generated by Django 5.1.3 on 2024-11-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_mobilizetie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilizetie',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
