# Generated by Django 5.1.3 on 2024-11-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_brigade_brigade2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brigade2',
            new_name='Brigade',
        ),
    ]
