# Generated by Django 5.1.3 on 2024-11-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_mobilizetie_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilizetie',
            name='nr2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
