# Generated by Django 5.1.3 on 2024-11-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_brigade2_brigade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brigade',
            name='nr',
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
