# Generated by Django 5.1.3 on 2024-11-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_mobilizetie_nr2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilizetie',
            name='nr',
        ),
        migrations.RemoveField(
            model_name='mobilizetie',
            name='nr2',
        ),
    ]
