# Generated by Django 5.1.3 on 2024-11-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_brigade_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brigade',
            name='ordeņa_pakape',
            field=models.CharField(blank=True, null=True),
        ),
    ]
