# Generated by Django 5.1.3 on 2024-11-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_mobilizetie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobilizetie',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('uzvards', models.CharField(blank=True, max_length=100, null=True)),
                ('vards', models.CharField(blank=True, max_length=100, null=True)),
                ('pirmā_dienesta_pakāpe', models.CharField(blank=True, max_length=100, null=True)),
                ('dzimsanas_datums', models.DateField(blank=True, null=True)),
                ('dzimsanas_vieta', models.CharField(blank=True, max_length=255, null=True)),
                ('kritis_datums', models.DateField(blank=True, null=True)),
                ('info_par_krisanu', models.TextField(blank=True, null=True)),
                ('pazudis_datums', models.DateField(blank=True, null=True)),
                ('info_par_pazusanu', models.TextField(blank=True, null=True)),
                ('miris_datums', models.DateField(blank=True, null=True)),
                ('info_par_mirsanu', models.TextField(blank=True, null=True)),
                ('kritis_gusta_datums', models.DateField(blank=True, null=True)),
                ('cits_naves_iemesls_datums', models.DateField(blank=True, null=True)),
                ('iemesls', models.TextField(blank=True, null=True)),
                ('mobilizesanas_datums_labots', models.CharField(blank=True, max_length=255, null=True)),
                ('pedeja_dzives_vieta', models.CharField(blank=True, max_length=255, null=True)),
                ('pirmā_dienesta_vieniba_labots', models.CharField(blank=True, max_length=255, null=True)),
                ('nosutits_uz_citu_vienibu_kursiem', models.CharField(blank=True, max_length=255, null=True)),
                ('aizbraucis_uz_lpsr', models.BooleanField(default=False)),
                ('paaugstinats_degradets', models.CharField(blank=True, max_length=255, null=True)),
                ('dezertējis_datums', models.DateField(blank=True, null=True)),
                ('atbrīvots_no_dienesta_datums', models.DateField(blank=True, null=True)),
                ('atbrivosanas_iemesls', models.CharField(blank=True, max_length=255, null=True)),
                ('ievainots', models.TextField(blank=True, null=True)),
                ('navessods_arests', models.CharField(blank=True, max_length=255, null=True)),
                ('apbalvots', models.TextField(blank=True, null=True)),
                ('cita_informacija', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
