# Generated by Django 5.1.3 on 2024-11-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_brigade_ordeņa_pakape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='department',
        ),
        migrations.RemoveField(
            model_name='react',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='react',
            name='id',
        ),
        migrations.AddField(
            model_name='react',
            name='arhīva_lieta',
            field=models.CharField(default='Default Value', max_length=50),
        ),
        migrations.AddField(
            model_name='react',
            name='dienesta_vieniba',
            field=models.CharField(default='Default Value', max_length=200),
        ),
        migrations.AddField(
            model_name='react',
            name='nr',
            field=models.CharField(default='Default Value', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='react',
            name='ordenis',
            field=models.CharField(default='Default Value', max_length=200),
        ),
        migrations.AddField(
            model_name='react',
            name='ordeņa_pakape',
            field=models.CharField(blank=True, default='Default Value', null=True),
        ),
        migrations.AddField(
            model_name='react',
            name='pakape',
            field=models.CharField(default='Default Value', max_length=100),
        ),
        migrations.AddField(
            model_name='react',
            name='piezimes',
            field=models.CharField(blank=True, default='Default Value', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='react',
            name='uzvards_un_vards',
            field=models.CharField(default='Default Value', max_length=200),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='ordenis',
            field=models.CharField(default='Default Value', max_length=200),
        ),
    ]
