# Generated by Django 5.1.3 on 2024-11-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_mobilizetie_nr_alter_mobilizetie_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mobilizetie',
        ),
    ]
