# Generated by Django 5.1.3 on 2024-11-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_mobilizetie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mobilizetie',
        ),
    ]
