# Generated by Django 5.1.3 on 2024-11-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_kritusie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kritusie',
        ),
    ]
