# Generated by Django 5.1.3 on 2024-11-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_kritusie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kritusie',
            fields=[
                ('nr', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rank', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('injury_or_death_date', models.CharField(max_length=100)),
                ('burial_place', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Soldier',
                'verbose_name_plural': 'Soldiers',
            },
        ),
    ]
