# Generated by Django 5.1.3 on 2024-11-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_kritusie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kritusie',
            old_name='nr',
            new_name='id',
        ),
    ]
