# Generated by Django 5.1.3 on 2024-11-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_nr_kritusie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kritusie',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
