# Generated by Django 5.1.3 on 2024-11-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_kritusie_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kritusie',
            name='burial_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
