# Generated by Django 5.1.3 on 2024-11-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_kritusie_burial_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kritusie',
            name='rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
