# Generated by Django 5.1.3 on 2024-11-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_kritusie_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kritusie',
            name='injury_or_death_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
