# Generated by Django 5.1.3 on 2024-11-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_kritusie_injury_or_death_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kritusie',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
