# Generated by Django 5.1.3 on 2024-11-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_mobilizetie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilizetie',
            name='aizbraucis_uz_lpsr',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
