# Generated by Django 5.1.3 on 2024-11-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_mobilizetie_dezertējis_datums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilizetie',
            name='miris_datums',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
