# Generated by Django 5.1.3 on 2024-11-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_mobilizetie_miris_datums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilizetie',
            name='atbrīvots_no_dienesta_datums',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
