# Generated by Django 5.1.3 on 2024-11-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_mobilizetie_aizbraucis_uz_lpsr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilizetie',
            name='kritis_gusta_datums',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
