# Generated by Django 5.1.3 on 2024-11-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_mobilizetie_uzvards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilizetie',
            name='uzvards',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
