# Generated by Django 5.1.3 on 2024-11-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_mobilizetie_uzvards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kritusie',
            options={},
        ),
        migrations.RenameField(
            model_name='kritusie',
            old_name='burial_place',
            new_name='apbedisanas_vieta',
        ),
        migrations.RenameField(
            model_name='kritusie',
            old_name='rank',
            new_name='dienesta_pakape',
        ),
        migrations.RenameField(
            model_name='kritusie',
            old_name='injury_or_death_date',
            new_name='kritis_un_miris_no_ievainojuma_un_kad',
        ),
        migrations.RenameField(
            model_name='kritusie',
            old_name='notes',
            new_name='piezimes',
        ),
        migrations.RenameField(
            model_name='kritusie',
            old_name='full_name',
            new_name='vards_uzvards',
        ),
        migrations.RenameField(
            model_name='kritusie',
            old_name='unit',
            new_name='vieniba',
        ),
    ]
