# Generated by Django 5.1.3 on 2024-11-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_kritusie_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='React',
        ),
    ]
