# Generated by Django 5.1.3 on 2024-11-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_delete_react'),
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('nr', models.CharField(default='Default Value', max_length=50, primary_key=True, serialize=False)),
                ('pakape', models.CharField(default='Default Value', max_length=100)),
                ('uzvards_un_vards', models.CharField(default='Default Value', max_length=200)),
                ('dienesta_vieniba', models.CharField(default='Default Value', max_length=200)),
                ('ordenis', models.CharField(default='Default Value', max_length=200)),
                ('ordeņa_pakape', models.CharField(blank=True, default='Default Value', null=True)),
                ('piezimes', models.CharField(blank=True, default='Default Value', max_length=255, null=True)),
                ('arhīva_lieta', models.CharField(default='Default Value', max_length=50)),
            ],
        ),
    ]
