# Generated by Django 5.1.3 on 2024-11-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_react'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zedelgema',
            name='dzimsanas_datums',
        ),
    ]
