# Generated by Django 5.1.3 on 2024-11-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_zedelgema_dzimsanas_datums'),
    ]

    operations = [
        migrations.AddField(
            model_name='zedelgema',
            name='dzimsanas_datums',
            field=models.DateField(blank=True, null=True),
        ),
    ]
