# Generated by Django 5.1.3 on 2024-11-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_delete_zedelgema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zedelgema',
            fields=[
                ('nr', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dienesta_pakape', models.CharField(max_length=50)),
                ('uzvards', models.CharField(max_length=50)),
                ('vards', models.CharField(max_length=50)),
                ('dzimsanas_datums', models.DateField(blank=True, null=True)),
                ('dienesta_vieniba', models.TextField()),
                ('nometnes_nodalijums', models.IntegerField()),
                ('aizbraucis_uz_psrs', models.CharField(blank=True, max_length=50, null=True)),
                ('miris', models.CharField(blank=True, max_length=50, null=True)),
                ('piezimes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
