# Generated by Django 5.1.3 on 2024-11-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_zedelgema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zedelgema',
        ),
    ]
