# Generated by Django 5.1.3 on 2024-12-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_appuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
