# Generated by Django 5.1.3 on 2024-12-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_remove_appuser_country_remove_appuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='username',
            field=models.CharField(default='Default Value', max_length=50),
        ),
    ]
