# Generated by Django 5.1.3 on 2024-12-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_appuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(default='Vārds', max_length=50),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(default='Uzvārds', max_length=50),
        ),
    ]
